### ISSUE TITLE
Label for Neurostars

### ISSUE THREAD

**Issue by emdupre** [brainhack101/neurolinks#21]
I was hoping to add a link to [Neurostars](http://neurostars.org), since I think it's a great resource for neuroimaging questions. But, I'm not sure what label to ascribe to it. Would you consider the forum a "tool" or an "initiative"? Or something else all together?

**Comment by gkiar** [comment]
Great point! Should we perhaps change "initiatives" to "communities"? What do you think?

**Comment by emdupre** [comment]
I like "communities"! BIDS and Neurostars are of very different scopes (for example), but I think they would both fall under that umbrella.

**Comment by gkiar** [comment]
Perfect, let's make that change then :)

**Comment by emdupre** [comment]
Opened #22 !

**Comment by gkiar** [comment]
💥
