### ISSUE TITLE
decide on name

### ISSUE THREAD

**Issue by gkiar** [brainhack101/neurolinks#7]
neurolinks is original, neurolynx is more clever...

Current plan: URL will stay neurolinks as it is move obvious to newcomers, but the name on the page will be lynx.

Feedback solicited.

**Comment by satra** [comment]
i guess this may show my age since lynx was one of my first "browsers" right after archie :)

if we wish to change the name, i suggest we do it now.

**Comment by gkiar** [comment]
I think links is more clear, and therefore the better answer, so I may just make the occasional lynx pun... :)
